apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
      tier: private-frontend
      track: stable
  template:
    metadata:
      labels:
        app: sample
        tier: private-frontend
        track: stable
    spec:
      containers:
      - name: sampleapp-container
        image: k8simagesregistery.azurecr.io/app:#{tag}#
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
---
apiVersion: v1
kind: Service
metadata:
  name: private-frontend
spec:
  selector:
    app: sample
    tier: private-frontend
  ports:
  - port: 8080
    targetPort: 80
  type: ClusterIP
